title: Zhuoran Zhang's Homepage
page-top-title: Zhuoran Zhang
top-section-bg-text: Geochemistry
home-subtitle: Zhuoran Zhang&ensp;|&ensp;张卓然
copyright-text: '&copy; Zhuoran Zhang 2025. All Rights Reserved.'
