title: 张卓然&ensp;|&ensp;Zhuoran Zhang
page-top-title: Zhuoran Zhang
top-section-bg-text: <em>Lost in Daydreams</em> & <br><em>Geochemistry</em>
home-subtitle: 张卓然&ensp;|&ensp;Zhuoran Zhang
copyright-text: '&copy; Copyright 2025 张卓然 Zhuoran Zhang. Last updated: October, 2025.'
